name: Airline CI-CD

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - test

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: airline-devops
  IMAGE_TAG: latest

jobs:

  ci-cd:
    name: Lint, Test, Build, Scan and Push
    runs-on: ubuntu-latest

    steps:

      # -----------------------------
      # 1. CHECKOUT CODE
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4


      # -----------------------------
      # 2. SETUP PYTHON
      # -----------------------------
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip


      # -----------------------------
      # 3. INSTALL DEPENDENCIES
      # -----------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # -----------------------------
      # 4. LINT
      # -----------------------------
      - name: Run lint
        run: |
          ruff check .

      - name: Test Python import
        run: |
         python -c "import app; print(app)"
         python -c "from app.app import app; print(app)"
      # -----------------------------
      # 5. RUN TESTS
      # -----------------------------
      - name: Run tests
        run: |
          python -m pytest -v


      # -----------------------------
      # 6. BUILD DOCKER IMAGE
      # -----------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t airline-devops:${{ env.IMAGE_TAG }} .


      # -----------------------------
      # 7. TRIVY SECURITY SCAN
      # -----------------------------
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: airline-devops:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Get GitHub repository information
        run: |
         echo "Repository: $GITHUB_REPOSITORY"
         echo "Repository ID: ${{ github.repository_id }}"
         echo "Repository owner ID: ${{ github.repository_owner_id }}"
         echo "Ref: $GITHUB_REF"
      # -----------------------------
      # 8. CONFIGURE AWS
      # -----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      # -----------------------------
      # 9. LOGIN TO ECR
      # -----------------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # -----------------------------
      # 10. TAG IMAGE
      # -----------------------------
      - name: Tag image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag \
            airline-devops:${{ env.IMAGE_TAG }} \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}


      # -----------------------------
      # 11. PUSH IMAGE TO ECR
      # -----------------------------
      - name: Push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
